### ISSUE TITLE
Solved : command 'arm-linux-gnueabihf-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by vincent-56** [knro/indiwebmanager#28]
Hi Jasem,
I'm using indi, ekos and kstar since many years, so many thanks for ur great work.
I tried to install indiwebmanager to avoid connecting on SSH to my Pi and I got this error : error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

It comes from the C compilation with arm-linux-gnueabihf-gcc of sutil/_psutil_common.c, look

---
psutil/_psutil_common.c:9:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
 #include <Python.h>
                    ^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
---

In order to avoid that, I needed to install python-dev (apt install python-dev).

I will not open a PR for that ;)
Hope it could help others people,
And great job again !

If u need some help for the future, will be a pleasure to help u and the team, 
Vincent

**Comment by agners** [comment]
You were using PIP I assume? In that case, Python probably tries to install psutil using pip. Installing the Debian package `python-psutils` will resolve your issue too and probably be faster.

I installed those packages before using pip3 to install `indiweb`:

```
apt-get update python3-pip python3-setuptools python3-psutil python3-bottle python3-requests
```
