### ISSUE TITLE
Add support for ser2net

### ISSUE THREAD

**Issue by agners** [knro/indiwebmanager#33]
For mounts which use serial port it would be a nice addition to enable ser2net. This can be useful e.g. for firmware upgrade or to support application which connect directly to a Celestron mount.

**Comment by knro** [comment]
It's already possible to connect to mount that is available over TCP/IP using ser2net or natively. Have you tested connecting to the mount this way?

**Comment by agners** [comment]
Sorry, I was probably not quite clear: I meant it would be nice to enable ser2net on mounts which are connected locally on a serial port.

E.g. for Celestron, forwarding the serial port directly using ser2net allows to use SkySafari. As far as I understand this only works if SkySafari can talk to the mount directly (e.g. using ser2net) and not via INDI....

**Comment by knro** [comment]
Ok. Well, this is an INDI issue to begin with, not indiwebmanager issue. Also, I think this is an extra step that does not belong at the INDI driver layer
