### ISSUE TITLE
Reboot and PowerOff options in indi-web

### ISSUE THREAD

**Issue by Chris-Rowland** [knro/indiwebmanager#38]
Could web options be added to reboot and power off the system running indi-web.

At present full set up and configuration can be done from indi-web but at the end of the evening the only way to shut down is to use ssh to shut down.  Options in indi-web to do this would be very useful. It would help to automate the system shut down from Ekos.

I'll have a look but my Python is minimal.

Chris

**Comment by knro** [comment]
I think it can be easily implemented. Just add a new restful call.. e.g.

Something like this.

@app.post('/api/system/shutdown')
def system_shutdown():
   subprocess.run("systemctl poweroff")

Then in the javascript and template files, add the appropriate button to call this POST operation and it's done!
