### ISSUE TITLE
Indi-server startup command line options should be configurable

### ISSUE THREAD

**Issue by AlejandroJorgePerez** [knro/indiwebmanager#45]
https://github.com/knro/indiwebmanager/blob/d7bb6693d9113b84ce1d6aaf6e93873fec441810/indiweb/indi_server.py#L30

For newer cameras (full frame, large megapixels) the "-m 100" hardcoded option makes downloads most pictures fail. The server (in my case) needs to be started with at least "-m 256 -d 128". It would be nice if these options can be configured somehow.

**Comment by knro** [comment]
Right, though now it's easier to increase this limit.

**Comment by chrysikos** [comment]
I have ASI6200 and I have the same problem? How can I fix it?

**Comment by knro** [comment]
It's fixed now, increased limit to 1000.
