### ISSUE TITLE
Moving bottle out - requirements.txt

### ISSUE THREAD

**Issue by ppapadeas** [knro/indiwebmanager#5]
I suggest we move bottle.py out of the directory and call it in as a requirement to be installed through a requirements.txt and pip.

@knro let me know if you want me to open the PR, creating the requirements.txt and updating the readme.

**Comment by knro** [comment]
Is bottle.py readily available?? i.e. users won't have to dig for it? just use pip?

**Comment by ppapadeas** [comment]
Yep we can set it up to be fetched by pip (together with other requirements). I will make a PR with the changes and updating the README
