### ISSUE TITLE
Missing /usr/share/indi/indi_rpicam.xml

### ISSUE THREAD

**Issue by sajmons** [knro/indiwebmanager#52]
Raspbery PI HQ camera isn't listed inside indiwebmanager camera list. User shuld manually download https://github.com/indilib/indi-3rdparty/blob/master/indi-rpicam/indi_rpicam.xml.cmake and copy it to /usr/share/indi/indi_rpicam.xml and restart indiwebmanager or device.

For more information see:
https://indilib.org/forum/ekos/9016-raspberrypi-hq-camera-does-not-show-in-indi-web-manager.html

**Comment by knro** [comment]
This is not related to the web manager, the driver itself must be installed and then the web manager would detect it.

**Comment by sajmons** [comment]
It is then indi_rpicam driver issue, because driver is correctly installed.
